const { useState, useEffect } = React;

function App() {
  const [tgId, setTgId] = useState("548920134"); // Тестовый ID
    const [nickname, setNickname] = useState('');
      const [faction, setFaction] = useState('multigaming');
        const [error, setError] = useState('');
          const [success, setSuccess] = useState(false);
            const [loading, setLoading] = useState(false);

              // Подтягиваем настоящий ID из Telegram, если открыли в телеге
                useEffect(() => {
                    if (window.Telegram?.WebApp?.initDataUnsafe?.user?.id) {
                          setTgId(window.Telegram.WebApp.initDataUnsafe.user.id.toString());
                              }
                                  // Кнопка расширения приложения на весь экран ТГ
                                      window.Telegram?.WebApp?.expand();
                                        }, []);

                                          const validateNickname = (name) => {
                                              const regex = /^[A-Z][a-z]+_[A-Z][a-z]+$/;
                                                  return regex.test(name);
                                                    };

                                                      const handleRegister = (e) => {
                                                          e.preventDefault();
                                                              setError('');
                                                                  setLoading(true);

                                                                      if (!validateNickname(nickname)) {
                                                                            setError('Неверный формат! Нужен стиль Nick_Name (например, Misha_Top)');
                                                                                  setLoading(false);
                                                                                        return;
                                                                                            }

                                                                                                // Имитация отправки данных
                                                                                                    setTimeout(() => {
                                                                                                          if (nickname === "Admin_Admin") {
                                                                                                                  setError('Этот режиссер уже зарегистрирован!');
                                                                                                                          setLoading(false);
                                                                                                                                } else {
                                                                                                                                        setSuccess(true);
                                                                                                                                                setLoading(false);
                                                                                                                                                      }
                                                                                                                                                          }, 1000);
                                                                                                                                                            };

                                                                                                                                                              if (success) {
                                                                                                                                                                  return (
                                                                                                                                                                        <div style={styles.container}>
                                                                                                                                                                                <div style={styles.card}>
                                                                                                                                                                                          <h2 style={{...styles.title, color: '#4BB543'}}>🎬 Кастинг пройден!</h2>
                                                                                                                                                                                                    <p style={styles.text}>Вы успешно добавлены в съёмочную группу!</p>
                                                                                                                                                                                                              <div style={styles.infoBox}>
                                                                                                                                                                                                                          <p><b>Ваш ник:</b> {nickname}</p>
                                                                                                                                                                                                                                      <p><b>Статус:</b> {
                                                                                                                                                                                                                                                    faction === 'multigaming' ? 'Участник Multigaming' :
                                                                                                                                                                                                                                                                  faction === 'yakudza' ? 'Yakudza Respachi' : 'Приглашенный участник'
                                                                                                                                                                                                                                                                              }</p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                  <div style={styles.container}>
                                                                                                                                                                                                                                                                                                                        <div style={styles.card}>
                                                                                                                                                                                                                                                                                                                                <h1 style={styles.title}>🎥 Регистрация Киностудии</h1>
                                                                                                                                                                                                                                                                                                                                        <p style={styles.subtitle}>Пройдите верификацию для участия в ивенте</p>

                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleRegister} style={styles.form}>
                                                                                                                                                                                                                                                                                                                                                          <div style={styles.inputGroup}>
                                                                                                                                                                                                                                                                                                                                                                      <label style={styles.label}>Ваш Telegram ID</label>
                                                                                                                                                                                                                                                                                                                                                                                  <input type="text" value={tgId} readOnly style={styles.inputDisabled} />
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                      <div style={styles.inputGroup}>
                                                                                                                                                                                                                                                                                                                                                                                                                  <label style={styles.label}>Никнейм в BLACK RUSSIA (Nick_Name)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                              <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                            type="text" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Например: Misha_Top" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={nickname} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setNickname(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={styles.input} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={styles.inputGroup}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label style={styles.label}>Ваше положение</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select value={faction} onChange={(e) => setFaction(e.target.value)} style={styles.select}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="multigaming">Участник Multigaming</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="yakudza">Yakudza Respachi</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="guest">Приглашенный участник</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && <div style={styles.error}>{error}</div>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" disabled={loading} style={styles.button}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Проверка...' : 'Занять кресло режиссера'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Стили оставляем те же самые (встроенные для телефона)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          container: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', backgroundColor: '#121214', fontFamily: 'sans-serif', padding: '15px', color: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            card: { backgroundColor: '#1a1a1e', borderRadius: '16px', padding: '24px', width: '100%', maxWidth: '400px', border: '1px solid #2a2a30' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: { fontSize: '22px', fontWeight: 'bold', textAlign: 'center', marginBottom: '8px', color: '#e5e5e5' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitle: { fontSize: '14px', textAlign: 'center', color: '#7a7a85', marginBottom: '24px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text: { textAlign: 'center', color: '#aaa', marginBottom: '15px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    form: { display: 'flex', flexDirection: 'column', gap: '16px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      inputGroup: { display: 'flex', flexDirection: 'column', gap: '6px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label: { fontSize: '12px', color: '#7a7a85' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          input: { backgroundColor: '#26262b', border: '1px solid #3a3a42', borderRadius: '8px', padding: '12px', color: '#fff', fontSize: '15px', outline: 'none' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            inputDisabled: { backgroundColor: '#161619', border: '1px solid #222226', borderRadius: '8px', padding: '12px', color: '#5a5a65', fontSize: '15px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              select: { backgroundColor: '#26262b', border: '1px solid #3a3a42', borderRadius: '8px', padding: '12px', color: '#fff', fontSize: '15px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                button: { backgroundColor: '#e11d48', color: '#fff', border: 'none', borderRadius: '8px', padding: '14px', fontSize: '16px', fontWeight: 'bold', marginTop: '10px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  error: { backgroundColor: 'rgba(239, 68, 68, 0.1)', border: '1px solid #ef4444', color: '#ef4444', borderRadius: '8px', padding: '10px', fontSize: '13px', textAlign: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    infoBox: { backgroundColor: '#26262b', padding: '15px', borderRadius: '8px', fontSize: '14px' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const root = ReactDOM.createRoot(document.getElementById('root'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    root.render(<App />);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    constconst